### ISSUE TITLE
Deploy to App Store

### ISSUE THREAD

**Issue by rkho** [rkho/product-hunt-react-native#46]
Making a note to deploy to App Store once complete (within the next two weeks is ideal)

**Comment by spritle** [comment]
@rkho Is this same as https://itunes.apple.com/in/app/product-hunt-best-new-products/id904658671?mt=8 or You guys are creating a complimentary app using react-native?

**Comment by rkho** [comment]
Hi!

I built a complimentary app using React Native. It's live! https://itunes.apple.com/us/app/product-kitty/id1018558174?ls=1&mt=8

**Comment by rkho** [comment]
Closing this issue because it's now deployed

**Comment by spritle** [comment]
Thanks @rkho
